### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by Bogdanp**
I noticed after my last PR that the CI for this repo still relies on (the now-defunct-for-open-source) Travis CI. So, this change removes Travis CI support and adds a GitHub actions workflow to test the code on every push.

The old CI tested Racket versions all the way back to 6.1, but at some point (IIRC around 6.8), the SSL machinery bitrotted and those old versions can no longer install packages. So, the minimum version that is tested in the new workflow is 6.11, alongside the current stable version (8.11.1 as of this PR) and the most recent snapshot (as of the time each workflow runs).

### CODE REVIEW

**Comment by Bogdanp** [comment]
I was playing with adding some property-based tests to the repo and I noticed my last change introduced a bug in `cookie-value?`, namely I forgot to add the backtick character to the regexp. I've added a fix and the new property-based tests here, but let me know if you'd like me to make separate PRs for the fix, the CI updates and the property-tests (or if you'd like me to drop either). Apologies for the noise during the holidays!

**Comment by RenaissanceBug** [comment]
I am _delighted_. "Replace Travis" was on my TODO list, a fact I was reminded of last night while reviewing PR#15, and I somewhat dreaded the open-ended task of choosing and learning the replacement machinery. So, thanks!

I was unfamiliar with your rackcheck library--I've been out of racketland for a few years--and it's a pleasure to see good PBT facilities in Racket.

Give me a few days to get back to the laptop and do my due diligence on this, and I'll get it merged. If you want to split off the backtick commit as a quickfix I can merge separately, I'm comfortable doing that from the phone app and can get it in place faster. Otherwise I'll just merge them all at once in a few days.

Thanks again!

**Comment by Bogdanp** [comment]
I've opened #17 as a minimal fix for the backtick issue. Once that's merged (no rush), I'll rebase this PR on top of the master branch. Thanks!

**Comment by Bogdanp** [comment]
Hi @RenaissanceBug, I just wanted to ping you on this PR again so it doesn't get lost. Happy to make any changes!

**Comment by RenaissanceBug** [comment]
Hi @Bogdanp ! Thanks for the nudge. I looked it over and will merge. Thanks again for your work.

**Pull request merged**
