### PR TITLE
Split package into -lib, -test, and -doc variants

### PR DESCRIPTION
**Pull request by LiberalArtist**
(Needed so that `web-server` can depend on this: [https://github.com/racket/web-server/pull/21](https://github.com/racket/web-server/pull/21))

The package catalog will also need to be updated to reflect this change.

### CODE REVIEW

**Comment by jeapostrophe** [comment]
@RenaissanceBug I am happy to join this repo as a manager if you'd like me to review this, in case you are busy.

**Comment by RenaissanceBug** [comment]
Thanks, Jay — I'm tied up with school work and wouldn't have been able to get to this for a while.

I added you as a collaborator; let me know if there's anything more you need me to do in order for you to have the access you need.

**Comment by jeapostrophe** [comment]
@LiberalArtist You need to update `.travis.yml` for a new script to install the three packages

**Comment by LiberalArtist** [comment]
I've done what I think should be the right thing, but I should note that I haven't actually worked with `.travis.yml` before.

**Comment by jeapostrophe** [comment]
`net-cookies-test` had an error in its `update-implies` field, which must be a subset of the dependencies. Did you mean to include `web-server-lib`?

**Comment by jeapostrophe** [comment]
Note to myself: Apply with https://github.com/racket/web-server/pull/22

**Comment by LiberalArtist** [comment]
Thanks; I meant `net-cookies-lib`.

**Comment by jeapostrophe** [comment]
@RenaissanceBug please add me as an author here: https://pkgd.racket-lang.org/pkgn/package/net-cookies so I can update the source on the server

**Comment by jeapostrophe** [comment]
@RenaissanceBug Actually, it looks like I can hack the planet and do it.

**Pull request merged**
