### PR TITLE
Relicense this repository under the Apache v2 and MIT licenses.

### PR DESCRIPTION
**Pull request by samth**
This follows the general Racket relicensing effort;
see racket/racket#1570.

All the other contributors to this repository have signed off on
changing the license of their Racket contributions.

### CODE REVIEW

**Comment by samth** [comment]
This also needs permission from @mebassett.

**Comment by RenaissanceBug** [comment]
@Samth — let me know if you need any action from me, beyond a simple written consent. (Yes, I do consent to this licensing change as regards all my contributions to the repo.)

**Comment by samth** [comment]
I'd like to get permission from @mebassett and then you could merge this pull request.

**Comment by RenaissanceBug** [comment]
Okay. I’ll watch for an update confirming @mebassett has given permission, then merge it.

**Comment by samth** [comment]
I got email from @mebassett off-github confirming permission, so this is good to merge.

**Pull request merged**
